-- ╔══════════════════════════════════════════════════════════════════╗
-- ║ SkyForce — multiplayer lobby schema (Step 2 of rollout)          ║
-- ╚══════════════════════════════════════════════════════════════════╝
--
-- This is the MVP schema for the lobby + shared-game-state subsystem.
-- The engine still owns the rich GameState shape (typed in
-- src/types/game.ts); we serialize the whole thing as JSON in
-- `game_state.state_json` for now. Once the lobby flow is stable
-- a future migration will normalize teams / routes / fleet into
-- their own tables, but JSON is faster and safer while the engine
-- is still moving.
--
-- Anonymous-friendly play. There is NO Supabase auth user — players
-- get a stable per-browser id (crypto.randomUUID) stored in
-- localStorage and sent as a header on every server-mediated write.
-- Server-side API routes are the authoritative mutation path; RLS
-- below is intentionally permissive for MVP and will tighten as the
-- API surface lands.
--
-- ──────────────────────────────────────────────────────────────────
-- Concurrency model
-- ──────────────────────────────────────────────────────────────────
-- Every game row carries a `version` integer. Clients send their
-- last-seen version on every write (UPDATE … WHERE version = $expected).
-- A 0-row update means "stale write — refresh and retry." The state
-- update + version bump happen in the same statement so two browsers
-- can't clobber each other's submission. See lib/games/api.ts for the
-- canonical write helpers.
--

create extension if not exists "pgcrypto";

-- ╭──────────────────────────────────────────────────────────────────╮
-- │ games                                                            │
-- ╰──────────────────────────────────────────────────────────────────╯
-- One row per lobby/run. Lifecycle: 'lobby' → 'playing' → 'ended'.
-- The mode/visibility flags drive every UI gate (Board Decisions,
-- public lobby listing, etc).
create table if not exists public.games (
  id                          uuid primary key default gen_random_uuid(),
  name                        text not null,
  mode                        text not null check (mode in ('facilitated', 'self_guided')),
  visibility                  text not null check (visibility in ('public', 'private')),
  status                      text not null default 'lobby'
                              check (status in ('lobby', 'playing', 'ended')),
  -- 4-digit join code for private lobbies. Null for public games.
  -- Generated by the API at create-time and unique within active games.
  join_code                   text,
  max_teams                   integer not null default 6
                              check (max_teams between 1 and 12),
  current_quarter             integer not null default 1
                              check (current_quarter between 1 and 40),
  board_decisions_enabled     boolean not null default false,
  -- Browser session ids of host + facilitator. Anonymous; not
  -- references to auth.users. Distinct because a self-guided host
  -- is NOT a facilitator (no Board Decisions, no live-sim controls).
  created_by_session_id       text not null,
  facilitator_session_id      text,
  locked                      boolean not null default false,
  started_at                  timestamptz,
  ended_at                    timestamptz,
  -- Optimistic-concurrency token. Bumped on every server-mediated
  -- mutation. See game_state.version for the heavy state token.
  version                     integer not null default 1,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now()
);

create index if not exists games_visibility_status_idx
  on public.games (visibility, status)
  where visibility = 'public';

create unique index if not exists games_join_code_active_idx
  on public.games (join_code)
  where join_code is not null and status <> 'ended';

create index if not exists games_creator_idx
  on public.games (created_by_session_id);

-- ╭──────────────────────────────────────────────────────────────────╮
-- │ game_members                                                     │
-- ╰──────────────────────────────────────────────────────────────────╯
-- One row per (game, browser session) pairing. The lobby renders
-- seats from this table; the engine reads team.claimedBySessionId
-- as the runtime authority but they're kept in sync by the claim
-- mutation.
create table if not exists public.game_members (
  id              uuid primary key default gen_random_uuid(),
  game_id         uuid not null references public.games(id) on delete cascade,
  session_id      text not null,
  role            text not null default 'player'
                  check (role in ('player', 'host', 'facilitator', 'spectator')),
  -- Team id (in the engine state) this member controls. Null for
  -- spectators or members who haven't claimed a seat yet.
  team_id         text,
  display_name    text,
  connected_at    timestamptz not null default now(),
  last_seen_at    timestamptz not null default now(),
  -- A single browser can occupy at most one seat per game.
  unique (game_id, session_id)
);

create index if not exists game_members_game_idx on public.game_members (game_id);
create index if not exists game_members_session_idx on public.game_members (session_id);

-- ╭──────────────────────────────────────────────────────────────────╮
-- │ game_state                                                       │
-- ╰──────────────────────────────────────────────────────────────────╯
-- Snapshot of the full engine GameState as JSON. One row per game.
-- Updated on every quarter close + every server-mediated team
-- mutation. The version column is the optimistic-concurrency token.
create table if not exists public.game_state (
  game_id      uuid primary key references public.games(id) on delete cascade,
  version      integer not null default 1,
  state_json   jsonb not null,
  updated_at   timestamptz not null default now()
);

-- ╭──────────────────────────────────────────────────────────────────╮
-- │ game_events                                                      │
-- ╰──────────────────────────────────────────────────────────────────╯
-- Audit log. Every meaningful action — join, start, lock, ready,
-- close, decision-submit, facilitator-override — writes a row here.
-- Append-only, never updated. The facilitator console reads this
-- as a timeline; analytics later.
create table if not exists public.game_events (
  id                  uuid primary key default gen_random_uuid(),
  game_id             uuid not null references public.games(id) on delete cascade,
  actor_session_id    text,
  actor_team_id       text,
  type                text not null,
  payload_json        jsonb not null default '{}'::jsonb,
  created_at          timestamptz not null default now()
);

create index if not exists game_events_game_created_idx
  on public.game_events (game_id, created_at desc);

create index if not exists game_events_type_idx on public.game_events (type);

-- ╭──────────────────────────────────────────────────────────────────╮
-- │ updated_at trigger                                               │
-- ╰──────────────────────────────────────────────────────────────────╯
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists games_set_updated_at on public.games;
create trigger games_set_updated_at
  before update on public.games
  for each row execute function public.set_updated_at();

drop trigger if exists game_state_set_updated_at on public.game_state;
create trigger game_state_set_updated_at
  before update on public.game_state
  for each row execute function public.set_updated_at();

-- ╭──────────────────────────────────────────────────────────────────╮
-- │ Row-Level Security                                               │
-- ╰──────────────────────────────────────────────────────────────────╯
-- Enabled but permissive for MVP. The authoritative mutation path is
-- server-side API routes using the service-role key (bypasses RLS).
-- Anon key reads are gated by these policies; we'll tighten them
-- once the API surface stabilizes.

alter table public.games          enable row level security;
alter table public.game_members   enable row level security;
alter table public.game_state     enable row level security;
alter table public.game_events    enable row level security;

-- Public games are listable by anyone (powers /lobby).
-- Private games are only readable when joined via code (read-by-id).
drop policy if exists games_read_public on public.games;
create policy games_read_public on public.games
  for select using (visibility = 'public');

drop policy if exists games_read_by_id on public.games;
create policy games_read_by_id on public.games
  for select using (true);  -- MVP: by-id reads are always allowed; the
                            -- API enforces join_code matching before
                            -- handing out the row id to the browser.

drop policy if exists game_members_read on public.game_members;
create policy game_members_read on public.game_members
  for select using (true);

drop policy if exists game_state_read on public.game_state;
create policy game_state_read on public.game_state
  for select using (true);

drop policy if exists game_events_read on public.game_events;
create policy game_events_read on public.game_events
  for select using (true);

-- Writes via anon key are blocked across the board. The server API
-- (using service-role) is the only writer. Drop these policies if
-- you want to allow direct browser writes during dev.
drop policy if exists games_no_anon_write on public.games;
create policy games_no_anon_write on public.games
  for all using (false) with check (false);

drop policy if exists game_members_no_anon_write on public.game_members;
create policy game_members_no_anon_write on public.game_members
  for all using (false) with check (false);

drop policy if exists game_state_no_anon_write on public.game_state;
create policy game_state_no_anon_write on public.game_state
  for all using (false) with check (false);

drop policy if exists game_events_no_anon_write on public.game_events;
create policy game_events_no_anon_write on public.game_events
  for all using (false) with check (false);
